config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end
  root to: "posts#index"

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :name, :message => " is required."
	validates_presence_of :email, :message => " is required (will not be published)."
	validates_presence_of :body, :message => " of comment is required."
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	has_attached_file :image, styles: { medium: '400x400>'},
										storage: :s3,
										s3_protocol:'https',
										s3_credentials: {
											bucket: 'megblog',
											access_key_id: ENV['S3_ACCESS_KEY'],
											secret_access_key: ENV['S3_SECRET_KEY']
										}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :title, :message => " is required."

  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@post = Post.find params[:post_id]
		@comment = Comment.new
	end

	def create
		@post = Post.find params[:post_id]
		@comment = @post.comments.new comment_params
		if @comment.save
			flash[:notice] = "Thank you for your comment"
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find params[:post_id]
		@comment = Comment.find params[:id]
	end

	def update
		@comment = Comment.find params[:id]
		@comment.update comment_params
		@comment.save
		flash[:notice] = "Comment successfully updated"
		redirect_to posts_path
	end

	def destroy
		@comment = Comment.find params[:id]
		@comment.destroy
		flash[:notice] = "Comment successfully deleted"
		redirect_to posts_path
	end


	def comment_params
		params.require(:comment).permit(:name, :email, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include ActionView::Helpers::TextHelper
	
	before_action :authenticate_user!, except: [:index, :show]

	def index
	  if params[:tag]
	    @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5).order(created_at: :desc)
	  else
			@posts = Post.all.paginate(:page => params[:page], :per_page => 4).order(created_at: :desc)
	  end

		@last_posts = @posts.first(5)
		@comment = Comment.new
		@comments = Comment.all.order(created_at: :desc)
		@last_comments = @comments.last(5)
		@post_months = Post.all.group_by{|t| t.created_at.beginning_of_month}
	end

	def show
		@posts = Post.all.order(created_at: :desc)
		@last_posts = @posts.first(5)
		@post = Post.find params[:id]
		@comments = Comment.all.order(created_at: :desc)
		@last_comments = @comments.last(5)
		@post_months = Post.all.group_by{|t| t.created_at.beginning_of_month}
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params
		@post.user = current_user
		if @post.save 
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		@post = Post.find params[:id]
		@post.update post_params
		@post.save
		flash[:notice] = "Post successfully updated"
		redirect_to posts_path
	end

	def destroy
		@post = Post.find params[:id]
		@comments = @post.comments
		@comments.each{|comment| comment.delete}
		@post.destroy
		flash[:notice] = "Post successfully deleted"
		redirect_to posts_path
	end

	def post_params
		params.require(:post).permit(:title, :description, :image, :tag_list, :italiandescription)		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def owner_of(post)
		(post.user.id == current_user.id) if current_user
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="col-sm-12 col-md-12">
  <p>
  <span class="glyphicon glyphicon-comment"></span> <%= pluralize(post.comments.length, "comment") %> &nbsp;
  <%= link_to "Leave a comment", new_post_comment_path(post), class: 'btn btn-sm btn-default leavecomment' %>
  </p>

  <div>
    <% if post.comments.any? %>
      <div class="clearfix">
        <ul id="comments" class="comments">
          <% post.comments.each do |comment| %>
            <li class="comment">
              <div class="clearfix">
                <span class="comment-author"><%= comment.name %> says</span>: <%= comment.body %>
                
                <small class="comment-date"><%= comment.created_at.strftime("%d %B %Y %H:%M") %></small>

                <% if owner_of(post) %>
                  <small><%= link_to "Edit this comment", edit_post_comment_path(post.id, comment) %></small>
                  <small><%= link_to "Delete this comment", post_comment_path(post.id, comment), method: :delete, 'data-confirm' => "Are you sure you want to delete this comment?" %></small>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

</div>

app/views/comments/_form.html.erb
<div class="col-md-12 col-sm-12 text-center">
<%= form_for [@post, @comment], url: { action: action } do |form| %>
  <% if @comment.errors.any? %>  
		<%= render 'posts/partials/formerrors', element: @comment %> 
  <% end %> 

	<div>
	<%= form.label :name %><br>(required)<br />
	<%= form.text_field :name %>
	</div>
	<div>
	<%= form.label :email %><br>(required - will not be published)<br />
	<%= form.text_field :email %>
	</div>
	<div>
	<%= form.label :body, "Leave your comment" %>(required)<br />
	<%= form.text_area :body %>
	</div>
	
<br>

	<div><%= form.submit "Submit" %></div>

<% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form', action: "update"  %>

app/views/comments/new.html.erb
<%= render 'form', action: "create" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Coderita</title>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'summernote-bs3', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'flag-icon.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'summernote.min', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">

</head>
<body>

<header class="navbar navbar-default bs-docs-nav navbar-fixed-top" role="banner">
  <div class="container">
    <%= render 'layouts/partials/togglenavigation' %>
    <%= render 'layouts/partials/usersession' %>
  </div>
</header>

<%= render 'layouts/partials/jumbotron' %>

<div id="body" class="container">

	<%= render 'layouts/partials/notice' %>

	<%= yield %>

</div>

<br>
</body>
</html>

app/views/layouts/partials/_jumbotron.html.erb
<div class="jumbotron text-center">
	<h1><%= link_to "Coderita", root_path %></h1>
	<p>A blog for parrots who love coding <img src="/images/Parrot.png"></p>
</div>

app/views/layouts/partials/_notice.html.erb
<!-- Alerts -->
<% if notice %>
  <p class="alert alert-info alert-dismissible">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger alert-dismissible">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= alert %>
  </p>
<% end %>
<!-- End of alerts -->

app/views/layouts/partials/_togglenavigation.html.erb
<div class="navbar-header">
	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	</button>
</div>

app/views/layouts/partials/_usersession.html.erb
<nav class="collapse navbar-collapse bs-navbar-collapse navbar-inner" role="navigation">
	<ul class="nav navbar-nav nav-center" id="coderita_navbar">
		<li><span  id="coderita_link"><%= link_to "Coderita", root_path %></span></li>
	</ul>
  <ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
			<li class="navbar-text">Welcome <%= current_user.name %></li>
			<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
		<% end %>
  </ul>
</nav>

app/views/posts/_form.html.erb
<%= form_for @post, url: { action: action }, html: {multipart: true, id: 'postform'} do |form| %>
  
  <% if @post.errors.any? %>  
		<%= render 'posts/partials/formerrors', element: @post %> 
  <% end %> 

	<section>
		<div>
			<%= form.label :title %><br />
			<%= form.text_field :title %>
		</div>
		<div>
				<%= form.label :image, "Upload your image" %>
				<%= form.file_field :image %>
		</div>
		<div>
				<%= form.label :tag_list, "Tags (separated by commas)" %><br />
		  	<%= form.text_field :tag_list%>
		</div>
		<div>
			<%= form.label :description %><br />
			<%= form.text_area :description, id: "summernote" %>
		</div>
		<br />

		<div><%= form.submit "Submit" %></div>
		<br>
		<p class="btn btn-primary" id="addita">Add italian version</p>
		<br>

		<!-- hidden -->
		<div id="versionita">
			<%= form.label :italiandescription, "Italian version" %><br />
			<%= form.text_area :italiandescription, id: "summernote-ita" %>
			<br />
			<p class="btn btn-danger" id="rmita">Remove italian version</p>
		</div>
		
	</section>
<% end %>


<script>
	$(document).ready(function() {
    $('#summernote').summernote({
      height: "300px"
    });
	});
</script>

app/views/posts/_post.html.erb
<article class="post_section">
  <h2>
  <%= link_to "#{post.title}", post_path(post) %>
  </h2>

  <div class="row">
    <%= render 'posts/partials/postedby', post: post %>
    <%= render 'posts/partials/editdelete', post: post %>
  </div>

  <div class="row">
    <%= render 'posts/partials/createdat', post: post %>
    <%= render 'posts/partials/tags', post: post %>
  </div>

  <div class="description">
  <%= render 'posts/partials/images', post: post %>
  <%= render 'posts/partials/description', post: post %>
  </div>

  <div class="row">
    <%= render 'posts/partials/like', post: post %>
    <%= render 'posts/partials/italianversion', post: post %>
    <%= render 'posts/partials/share', post: post %>
  </div>

  <div class="row">
    <%= render 'comments/comment', post: post %>
  </div>

</article>

app/views/posts/_posts.html.erb
<% if @posts.any? %>
	<h1>Latest posts</h1>
	<% @posts.each do |post| %>
		<%= render 'post', post: post %>

		
	<% end %>

<nav>
  <ul class="pager">
		<%= will_paginate @posts, :page_links => false %>
  </ul>
</nav>


<% else %>
	<h1>No posts yet</h1>
<% end %>

app/views/posts/_sidebar.html.erb
<!-- New post -->
<% if user_signed_in? %>
	<div class="text-center">
		<%= link_to "New post", new_post_path, class: "btn btn-primary btn-lg" %>
	</div>
	<br>
<% end %>

<!-- Tags -->

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Tags Cloud</h4>
  </div>
    <ul class="list-group">
      <li class="list-group-item text-center">
        <div id="tag_cloud">
          <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
        </div>
      </li>
    </ul>
</div>

<!-- Latest posts -->

<div class="panel panel-default">
  <div class="panel-heading">
      <h4>Latest Posts</h4>
  </div>
  <% if @posts.any? %>
    <ul class="list-group">
    	<% @last_posts.each do |post| %>
        <li class="list-group-item">
          <%= link_to "#{post.title}", post_path(post) %>
          (<%= post.created_at.strftime("%d %B %Y") %>)
        </li>
      <% end %>
    </ul>
  <% else %>
    <ul class="list-group">
      <li class='list-group-item'>No posts yet</li>
    </ul>
  <% end %>
</div>

<!-- Latest comments -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Latest comments</h4>
  </div>
  <% if @comments.any? %>
    <ul class="list-group">
      <% @last_comments.each do |comment| %>
        <li class="list-group-item">
          <span>"<%= comment.body %>"</span><br>
          <span><em><%= comment.name %> in <%= link_to "#{comment.post.title}", post_path(comment.post.id) %></em></span>
        </li>
      <% end %>
    </ul>
  <% else %>
    <ul class="list-group">
      <li class="list-group-item">No comments yet</li>
    </ul>
  <% end %>
</div>

<!-- Archive -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Archive</h4>
  </div>
  <% @post_months.sort.reverse.each do |month, posts| %>
    <ul class="list-group archive-posts">
      <li class="list-group-item archive-month"><%=h month.strftime("%B %Y") %></p>
      <% for post in posts %>
      <li class="list-group-item archive-post"><small><%=h link_to post.title %></small></li>
      <% end %>
    </ul>
  <% end %>
</div>


<!-- Tweets -->
<%= render 'shared/tweets' %>

<script type="text/javascript">
  $('li.archive-post').hide();
  $('li.archive-month').click(function(){
    $('li.archive-post').slideToggle();
  });
</script>

app/views/posts/edit.html.erb
<div class="text-center">
	<h1>Edit your post</h1>

	<%= render "form", action: "update" %>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8">
  	<%= render "posts" %>	
  </div>
  <div class="col-md-4">
  	<%= render "sidebar" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="text-center">
	<h1>New post</h1>

	<%= render "form", action: "create" %>
</div>

app/views/posts/partials/_createdat.html.erb
<div class="group1 col-sm-6 col-md-6">
	<span class="glyphicon glyphicon-time"></span> <%= post.created_at.strftime("%A %d %B %Y %H:%M") %>
</div>

app/views/posts/partials/_description.html.erb
<hr>
<div class="blogpost"><%= raw post.description %></div>
<div class="blogpostItalian"><%= raw(post.italiandescription) %></div>
<hr>

app/views/posts/partials/_editdelete.html.erb
<div class="group2 col-sm-6 col-md-6 editdelete">
	<% if owner_of(post) %>
		<span class="glyphicon glyphicon-edit"></span> <%= link_to "Edit post", edit_post_path(post) %>
		<span class="glyphicon glyphicon-trash"></span> <%= link_to "Delete post", post_path(post), method: :delete, 'data-confirm' => "Are you sure you want to delete this post?" %>
	<% end %>
</div>

app/views/posts/partials/_formerrors.html.erb
<p class="alert alert-danger alert-dismissible">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= pluralize(element.errors.count, "error") %> prohibited this form from being saved:<br>
  <% element.errors.full_messages.each do |msg| %>  
		<%= msg %>
  <% end %>
</p> 

app/views/posts/partials/_images.html.erb
<div class='text-center'>
	<% if post.image.present? %>
	  <%= image_tag post.image.url(:medium), class: 'uploaded-pic img-responsive' %>
	<% end %>
</div>

app/views/posts/partials/_italianversion.html.erb
<div class="col-md-6 col-sm-6 group2">
	<% if post.italiandescription.present? %>
	  <span class="label label-primary italianVersion myFlag">
	    italian version
	    <span class="flag flag-icon flag-icon-it"></span>
	  </span>

	  <span class="label label-primary englishVersion myFlag">
	  	english version
	  	<span class="flag flag-icon flag-icon-gb"></span>
	  </span>
	<% end %>
</div>

app/views/posts/partials/_like.html.erb
<div class="col-sm-6 col-md-6">
	<i class="glyphicon glyphicon-flash">Like</i>
</div>

app/views/posts/partials/_postedby.html.erb
<div class="group1 col-sm-6 col-md-6">
	<span class="glyphicon glyphicon-user"></span> Posted by <%= post.user.name %>
</div>

app/views/posts/partials/_share.html.erb
<div class="group1 col-sm-6 col-md-6"></div>
<div class="group2 col-sm-6 col-md-6">
  Share this post: <%= social_share_button_tag(post.title, popup: "true") %>
</div>

app/views/posts/partials/_tags.html.erb
<div class="group2 col-sm-6 col-md-6 tags">
	<span class="glyphicon glyphicon-tag"></span>
	Tags: <%= raw post.tag_list.map { |t, tag| link_to t, tag_path(t), class: 'tag' }.join(', ') %>
</div>

app/views/posts/partials/_tagscomments.html.erb
<div class="group2 col-sm-6 col-md-6">
	<span class="glyphicon glyphicon-bookmark"></span> <a href="#">Tags</a>, 
  <a href="#">Tags</a>, <a href="#">Tags</a>

  <!-- Comments -->
  <span class="glyphicon glyphicon-pencil"></span>
  <%= post.comments.length %> comments
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
		<%= render 'post', post: @post %>	
  </div>
  <div class="col-md-4">
  	<%= render "sidebar" %>
  </div>
</div>

app/views/shared/_tweets.html.erb
<section>
<a class="twitter-timeline" href="https://twitter.com/ShinyMali" data-widget-id="532275368342736896">Tweets by @ShinyMali</a>
</section>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>